export const columnMap = {
  auditLog: {
    id: 'ID',
    action: 'İşlem',
    resourceType: 'Kaynak Türü',
    resourceId: 'Kaynak ID',
    result: 'Sonuç',
    error: 'Hata',
    details: 'Detaylar',
    userId: 'Kullanıcı ID',
    createdAt: 'Tarih',
  },
  customerCard: {
    id: 'ID',
    sira: 'Sıra',
    name: 'Ünvan',
    sicil: 'Sicil',
    address: 'Adres',
    district: 'İlçe',
    region: 'Bölge',
    gsm1: 'GSM 1',
    contact1: 'İletişim 1',
    gsm2: 'GSM 2',
    contact2: 'İletişim 2',
    gsm3: 'GSM 3',
    contact3: 'İletişim 3',
    businessGroup: 'Meslek Grubu',
    color: 'Renk',
    status: 'Durum',
    authorizationDocument: 'Yetki Belge',
    vote: 'Oy',
    authorities: 'Yetkililer',
    salesRepresentative: 'Satış Temsilcisi',
    note: 'Not',
    createdAt: 'Oluşturulma Tarihi',
    updatedAt: 'Güncellenme Tarihi',
  },
  user: {
    id: 'ID',
    name: 'Ad',
    email: 'E-posta',
    emailVerified: 'E-posta Doğrulandı',
    image: 'Profil Resmi',
    createdAt: 'Oluşturulma Tarihi',
    updatedAt: 'Güncellenme Tarihi',
  },
  visit: {
    id: 'ID',
    date: 'Tarih',
    time: 'Saat',
    via: 'Aracılığıyla',
    note: 'Not',
    createdAt: 'Oluşturulma Tarihi',
    updatedAt: 'Güncellenme Tarihi',
  },
  businessGroupCard: {
    id: 'ID',
    businessGroupName: 'Meslek Grubu',
    uyeSayisi: 'Üye Sayısı',
    meclisSayisi: 'Meclis Sayısı',
    meclis1: 'Meclis 1',
    meclis2: 'Meclis 2',
    meclis3: 'Meclis 3',
    baskan: 'Komite 1',
    baskanYardimcisi: 'Komite 2',
    uye1: 'Komite 3',
    uye2: 'Komite 4',
    uye3: 'Meclis Yedek 1',
    uye4: 'Meclis Yedek 2',
    uye5: 'Meclis Yedek 3',
    yedekUye1: 'Komite Yedek 1',
    yedekUye2: 'Komite Yedek 2',
    yedekUye3: 'Komite Yedek 3',
    yedekUye4: 'Komite Yedek 4',
    yedekUye5: 'Yedek Üye 5',
    yedekUye6: 'Yedek Üye 6',
    yedekUye7: 'Yedek Üye 7',
    createdAt: 'Oluşturulma Tarihi',
    updatedAt: 'Güncellenme Tarihi',
  },
} as const;

export const getColumnName = <T extends keyof typeof columnMap>(
  table: T,
  column: keyof (typeof columnMap)[T],
) => {
  return columnMap[table][column];
};
