export const columnMap = {
  auditLog: [
    'id',
    'action',
    'resourceType',
    'resourceId',
    'result',
    'error',
    'details',
    'userId',
    'createdAt',
  ],
  customerCard: [
    'id',
    'sira',
    'name',
    'sicil',
    'address',
    'district',
    'region',
    'gsm1',
    'contact1',
    'gsm2',
    'contact2',
    'gsm3',
    'contact3',
    'businessGroup',
    'color',
    'status',
    'authorizationDocument',
    'vote',
    'authorities',
    'salesRepresentative',
    'note',
    'createdAt',
    'updatedAt',
  ],
  user: [
    'id',
    'name',
    'email',
    'emailVerified',
    'image',
    'createdAt',
    'updatedAt',
  ],
  visit: ['id', 'date', 'time', 'via', 'note', 'createdAt', 'updatedAt'],
  businessGroupCard: [
    'id',
    'businessGroupName',
    'uyeSayisi',
    'meclisSayisi',
    'meclis1',
    'meclis2',
    'meclis3',
    'baskan',
    'baskanYardimcisi',
    'uye1',
    'uye2',
    'uye3',
    'uye4',
    'uye5',
    'yedekUye1',
    'yedekUye2',
    'yedekUye3',
    'yedekUye4',
    'yedekUye5',
    'yedekUye6',
    'yedekUye7',
    'createdAt',
    'updatedAt',
  ],
} as const;
